In [86]:
import os

os.getcwd()
os.chdir("E:\\code\\6.MachineLearning\\1_KNN_algorithm\\data")
os.getcwd()

'E:\\code\\6.MachineLearning\\1_KNN_algorithm\\data'

In [87]:
import pandas as pd

df = pd.read_csv("iris.csv")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [89]:
X = df.iloc[:,:-1].values

In [90]:
y  = df.iloc[:,-1]
y.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [91]:
y.replace(['setosa', 'versicolor', 'virginica'],[0,1,2],inplace=True)

In [92]:
y = y.values

In [93]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [94]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [95]:
len(X_train)

105

In [96]:
len(X_test)

45

In [97]:
import numpy as np

np.unique(y_train, return_counts=True)

(array([0, 1, 2], dtype=int64), array([35, 35, 35], dtype=int64))

In [98]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train,y_train)

KNeighborsClassifier()

In [99]:
#KNeighborsClassifier?

In [100]:
y_pred_test = model.predict(X_test)
y_pred_test

array([2, 1, 2, 1, 2, 2, 1, 1, 0, 2, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 1, 0,
       1, 2, 2, 1, 1, 1, 1, 0, 2, 2, 1, 0, 2, 0, 0, 0, 0, 1, 1, 0, 1, 2,
       1], dtype=int64)

In [101]:
y_test

array([2, 1, 2, 1, 2, 2, 1, 1, 0, 2, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 1, 0,
       1, 2, 2, 1, 1, 1, 1, 0, 2, 2, 1, 0, 2, 0, 0, 0, 0, 1, 1, 0, 2, 2,
       1], dtype=int64)

In [102]:
sum(y_test == y_pred_test)

44

In [103]:
44/45*100

97.77777777777777

In [104]:
from sklearn.metrics import accuracy_score, confusion_matrix

accuracy_score(y_test, y_pred_test)

0.9777777777777777

In [105]:
confusion_matrix(y_test, y_pred_test)

array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  1, 14]], dtype=int64)

In [106]:
rs=[]
for i in list(range(2,21)):
    #print(i)
    for w in ['uniform','distance']:
        for alg in ['ball_tree', 'kd_tree', 'brute']:
            
            model = KNeighborsClassifier(n_neighbors=i, weights=w,algorithm=alg)
            model.fit(X_train,y_train)
            y_pred = model.predict(X_test)
            acc = accuracy_score(y_test,y_pred)
            rs.append((i,w,acc,alg))
    #print("n_neighbors:",i,"respective accuracy is:",acc)
rs

[(2, 'uniform', 0.9111111111111111, 'ball_tree'),
 (2, 'uniform', 0.9111111111111111, 'kd_tree'),
 (2, 'uniform', 0.9111111111111111, 'brute'),
 (2, 'distance', 0.9333333333333333, 'ball_tree'),
 (2, 'distance', 0.9333333333333333, 'kd_tree'),
 (2, 'distance', 0.9333333333333333, 'brute'),
 (3, 'uniform', 0.9555555555555556, 'ball_tree'),
 (3, 'uniform', 0.9555555555555556, 'kd_tree'),
 (3, 'uniform', 0.9555555555555556, 'brute'),
 (3, 'distance', 0.9555555555555556, 'ball_tree'),
 (3, 'distance', 0.9555555555555556, 'kd_tree'),
 (3, 'distance', 0.9555555555555556, 'brute'),
 (4, 'uniform', 0.9555555555555556, 'ball_tree'),
 (4, 'uniform', 0.9555555555555556, 'kd_tree'),
 (4, 'uniform', 0.9333333333333333, 'brute'),
 (4, 'distance', 0.9555555555555556, 'ball_tree'),
 (4, 'distance', 0.9555555555555556, 'kd_tree'),
 (4, 'distance', 0.9333333333333333, 'brute'),
 (5, 'uniform', 0.9777777777777777, 'ball_tree'),
 (5, 'uniform', 0.9777777777777777, 'kd_tree'),
 (5, 'uniform', 0.97777777777

In [107]:
from sklearn.model_selection import GridSearchCV

GridSearchCV?

In [109]:
model = KNeighborsClassifier(n_neighbors=8)
param_grid =  {"n_neighbors":list(range(2,21)),
                "weights":['uniform','distance'],
                "algorithm":['ball_tree', 'kd_tree', 'brute']}


In [119]:
clf = GridSearchCV(model, param_grid,cv=3)

In [125]:
clf.fit(X,y)

GridSearchCV(cv=3, estimator=KNeighborsClassifier(n_neighbors=8),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                         14, 15, 16, 17, 18, 19, 20],
                         'weights': ['uniform', 'distance']})

In [126]:
clf.cv_results_

{'mean_fit_time': array([0.00200152, 0.00316834, 0.00166821, 0.00100064, 0.0018367 ,
        0.00133435, 0.00200033, 0.00133403, 0.00183447, 0.00100072,
        0.00133467, 0.00133411, 0.00132998, 0.00134118, 0.00200137,
        0.00150148, 0.00150108, 0.00150116, 0.001501  , 0.00150975,
        0.00165971, 0.00167171, 0.0014952 , 0.00150069, 0.00150188,
        0.00165876, 0.00165923, 0.00150092, 0.00150132, 0.00150077,
        0.00150863, 0.00150967, 0.00150943, 0.00150053, 0.00150124,
        0.00150124, 0.00149258, 0.00149298, 0.001676  , 0.00183447,
        0.00233714, 0.00200176, 0.00199302, 0.00183463, 0.00165979,
        0.0015014 , 0.00183495, 0.00166798, 0.00200327, 0.0016679 ,
        0.00165931, 0.00166726, 0.00150911, 0.00200192, 0.00134071,
        0.00166925, 0.001827  , 0.00184345, 0.00183535, 0.00150188,
        0.00166829, 0.00216921, 0.00184345, 0.00150164, 0.00182676,
        0.00166837, 0.00217231, 0.00183185, 0.00166821, 0.00183479,
        0.00183511, 0.00182605,

In [127]:
clf.best_estimator_

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=4)

In [128]:
clf.best_score_

0.9866666666666667

In [129]:
clf.best_params_

{'algorithm': 'ball_tree', 'n_neighbors': 4, 'weights': 'uniform'}

In [132]:
kn_model = KNeighborsClassifier(algorithm= 'ball_tree', n_neighbors= 4, weights= 'uniform')
kn_model

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=4)

In [133]:
kn_model.fit(X_train, y_train)

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=4)

In [135]:
y_pred_test = kn_model.predict(X_test)

In [136]:
accuracy_score(y_test, y_pred_test)

0.9555555555555556

In [137]:
import pickle

pickle.dump(kn_model,open("k_model.pkl",'wb'))

In [142]:
loaded = pickle.load(open('k_model.pkl','rb'))

In [143]:
loaded.predict([[5.0,3.4,1.5,0.2]])

array([0], dtype=int64)