# Explore Toy_DataSets
- Scikit-learn comes with a few small standard datasets that do not require to download any file from some external website

#### For more: https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html#sklearn.datasets.load_iris
#### For more data sets refer: https://archive.ics.uci.edu/ml/index.php

## Exercise 1: Explore iris Dataset

In [94]:
from sklearn import datasets

print(len(dir(datasets)))
dir(datasets)

69


['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circles',
 'make_class

In [64]:
iris = datasets.load_iris()    # 01.Load iris data set

In [65]:
print(type(iris))              # 02.datatype of iris DataSet

<class 'sklearn.utils.Bunch'>


In [66]:
iris.keys()                    # 03. Keys of iris DataSet
#iris.values()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [67]:
iris.data[:10]                    # 04.observe iris data a.k.a features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [68]:
iris.target                   # 05.Observe iris target key

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [69]:
iris.target_names            # 06. Observe iris target_names key

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [70]:
print(iris.DESCR)            # 07.Observe iris descr

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [71]:
print(iris.feature_names)           # 08. Observe iris feature_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [72]:
print(iris.data.shape)              # 14. Nmber of rows and columns

(150, 4)


In [73]:
print(type(iris.data))              # 09. Datatype of iris data key
print(type(iris.target))            # 10. datatype of iris target key
print(type(iris.target_names))      # 11. datatype of iris target_names key
print(type(iris.DESCR))             # 12. datatype of iris descr key
print(type(iris.feature_names))     # 13. datatype of iris feature_names key

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'str'>
<class 'list'>


## Similarly Explore remaining toy DataSet's

In [74]:
for i in dir(datasets):
    if i.startswith("load_"):
        print(i)

load_boston
load_breast_cancer
load_diabetes
load_digits
load_files
load_iris
load_linnerud
load_sample_image
load_sample_images
load_svmlight_file
load_svmlight_files
load_wine


## Exercise 2: Create DataFrame from sklearn Bunch

In [75]:
from sklearn import datasets
import pandas as pd

print(" ##### 01. Load iris data set ##### ")
iris = datasets.load_iris()

print(" ##### 02. Create Data Frame ##### ")
#df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df = pd.DataFrame(data=iris["data"], columns=iris["feature_names"])
df.head(2)

 ##### 01. Load iris data set ##### 
 ##### 02. Create Data Frame ##### 


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2

In [76]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [77]:
df["classes"] = iris["target"]

In [78]:
df.iloc[[0,50,100]]          #for particular records

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
50                 7.0               3.2                4.7               1.4   
100                6.3               3.3                6.0               2.5   

     classes  
0          0  
50         1  
100        2

In [79]:
 iris["target_names"]

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [80]:
df.classes.replace([0,1,2],['setosa', 'versicolor', 'virginica'], inplace=True)
df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

  classes  
0  setosa  
1  setosa  
2  setosa

#### balanced data

In [81]:
import numpy as np

np.unique(iris["target"],return_counts=True)

(array([0, 1, 2]), array([50, 50, 50], dtype=int64))

## Exercise 3: Create a Bunch with our own data
-  Just Knowledge  purpose,not useful in live

In [1]:
import sklearn

dataset = sklearn.datasets.base.Bunch(data=[[80,6.2,10],[60,5.5,60]],
                                      target=["Male","Female"],
                                      feature_names=["weight","height","hair length"])
print(type(dataset))

AttributeError: module 'sklearn' has no attribute 'datasets'

In [96]:
dataset.keys()

NameError: name 'dataset' is not defined

In [97]:
dataset.data

NameError: name 'dataset' is not defined

In [98]:
dataset.feature_names

NameError: name 'dataset' is not defined

In [99]:
dataset.target

NameError: name 'dataset' is not defined