In [3]:
import os
os.chdir('E:/code/6.MachineLearning/3_Logistic_Regression')
os.getcwd()

'E:\\code\\6.MachineLearning\\3_Logistic_Regression'

In [4]:
import pandas as pd
df=pd.read_csv('carprice.csv')
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [5]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [6]:
#df.info

In [11]:
X=df.drop(['CarName','fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation','enginetype','cylindernumber','fuelsystem'],axis=1).values
X[:5]

array([[1.0000e+00, 3.0000e+00, 8.8600e+01, 1.6880e+02, 6.4100e+01,
        4.8800e+01, 2.5480e+03, 1.3000e+02, 3.4700e+00, 2.6800e+00,
        9.0000e+00, 1.1100e+02, 5.0000e+03, 2.1000e+01, 2.7000e+01,
        1.3495e+04],
       [2.0000e+00, 3.0000e+00, 8.8600e+01, 1.6880e+02, 6.4100e+01,
        4.8800e+01, 2.5480e+03, 1.3000e+02, 3.4700e+00, 2.6800e+00,
        9.0000e+00, 1.1100e+02, 5.0000e+03, 2.1000e+01, 2.7000e+01,
        1.6500e+04],
       [3.0000e+00, 1.0000e+00, 9.4500e+01, 1.7120e+02, 6.5500e+01,
        5.2400e+01, 2.8230e+03, 1.5200e+02, 2.6800e+00, 3.4700e+00,
        9.0000e+00, 1.5400e+02, 5.0000e+03, 1.9000e+01, 2.6000e+01,
        1.6500e+04],
       [4.0000e+00, 2.0000e+00, 9.9800e+01, 1.7660e+02, 6.6200e+01,
        5.4300e+01, 2.3370e+03, 1.0900e+02, 3.1900e+00, 3.4000e+00,
        1.0000e+01, 1.0200e+02, 5.5000e+03, 2.4000e+01, 3.0000e+01,
        1.3950e+04],
       [5.0000e+00, 2.0000e+00, 9.9400e+01, 1.7660e+02, 6.6400e+01,
        5.4300e+01, 2.8240e+03, 

In [12]:
y=df['CarName']
type(y)


pandas.core.series.Series

In [13]:
print(y.unique())
print(len(y.unique()))
print(list(range(0,23)))

['alfa-romero giulia' 'alfa-romero stelvio' 'alfa-romero Quadrifoglio'
 'audi 100 ls' 'audi 100ls' 'audi fox' 'audi 5000' 'audi 4000'
 'audi 5000s (diesel)' 'bmw 320i' 'bmw x1' 'bmw x3' 'bmw z4' 'bmw x4'
 'bmw x5' 'chevrolet impala' 'chevrolet monte carlo' 'chevrolet vega 2300'
 'dodge rampage' 'dodge challenger se' 'dodge d200' 'dodge monaco (sw)'
 'dodge colt hardtop' 'dodge colt (sw)' 'dodge coronet custom'
 'dodge dart custom' 'dodge coronet custom (sw)' 'honda civic'
 'honda civic cvcc' 'honda accord cvcc' 'honda accord lx'
 'honda civic 1500 gl' 'honda accord' 'honda civic 1300' 'honda prelude'
 'honda civic (auto)' 'isuzu MU-X' 'isuzu D-Max ' 'isuzu D-Max V-Cross'
 'jaguar xj' 'jaguar xf' 'jaguar xk' 'maxda rx3' 'maxda glc deluxe'
 'mazda rx2 coupe' 'mazda rx-4' 'mazda glc deluxe' 'mazda 626' 'mazda glc'
 'mazda rx-7 gs' 'mazda glc 4' 'mazda glc custom l' 'mazda glc custom'
 'buick electra 225 custom' 'buick century luxus (sw)' 'buick century'
 'buick skyhawk' 'buick opel isuzu 

In [170]:
y.replace(to_replace =['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda','isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault','saab', 'subaru', 'toyota', 'volkswagen', 'volvo'],
          value=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],inplace=True)



In [171]:
y.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22], dtype=int64)

In [172]:
type(X)

numpy.ndarray

In [173]:
y=y.values

In [174]:
type(y)

numpy.ndarray

In [175]:
from sklearn.model_selection import train_test_split

In [176]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [177]:
import numpy as np
np.unique(y,return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22], dtype=int64),
 array([ 3,  7,  8,  3,  9, 13,  4,  3, 17,  8,  1, 13, 18, 11,  7,  5,  2,
         6, 12, 32, 12, 11], dtype=int64))

In [178]:
np.unique(y_test,return_counts=True)

(array([ 2,  3,  4,  5,  6,  7,  9, 10, 12, 13, 14, 15, 16, 18, 19, 20, 21,
        22], dtype=int64),
 array([ 2,  2,  2,  3,  2,  1,  5,  4,  5,  9,  2,  1,  1,  1,  6, 11,  2,
         3], dtype=int64))

In [179]:
from sklearn.linear_model import LinearRegression

In [180]:
model=LinearRegression()
model

LinearRegression()

In [192]:
model.fit(X_train,y_train)


array([[ 1.6000e+01,  0.0000e+00,  1.0400e+02,  1.8900e+02,  6.7000e+01,
         5.6000e+01,  3.2300e+03,  2.0900e+02,  4.0000e+00,  3.0000e+00,
         8.0000e+00,  1.8200e+02,  5.4000e+03,  1.6000e+01,  2.2000e+01,
         3.0760e+04],
       [ 1.0000e+01,  0.0000e+00,  1.0000e+02,  1.7800e+02,  6.8000e+01,
         5.2000e+01,  3.0530e+03,  1.3100e+02,  3.0000e+00,  3.0000e+00,
         7.0000e+00,  1.6000e+02,  5.5000e+03,  1.6000e+01,  2.2000e+01,
         1.7859e+04],
       [ 1.0100e+02,  0.0000e+00,  9.7000e+01,  1.7300e+02,  6.5000e+01,
         5.5000e+01,  2.3020e+03,  1.2000e+02,  3.0000e+00,  3.0000e+00,
         8.0000e+00,  9.7000e+01,  5.2000e+03,  2.7000e+01,  3.4000e+01,
         9.5490e+03],
       [ 1.3300e+02,  3.0000e+00,  9.9000e+01,  1.8700e+02,  6.6000e+01,
         5.6000e+01,  2.6580e+03,  1.2100e+02,  4.0000e+00,  3.0000e+00,
         9.0000e+00,  1.1000e+02,  5.2500e+03,  2.1000e+01,  2.8000e+01,
         1.1850e+04],
       [ 6.9000e+01, -1.0000e+00,  1

In [194]:
y_test_pred=model.predict(X_test)
y_test_pred.round()

array([ 3.,  3., 13., 17.,  9., 13., 19., 20., 18., 21., 22., 20.,  9.,
       21., 10., 19.,  6., 11., 12., 18.,  9., 13., 13.,  7.,  5.,  3.,
       20., 23., 13., 22.,  8., 15., 19., 23., 11.,  9., 18.,  8.,  8.,
       11., 19.,  9., 15., 19., 13.,  6.,  5., 18., 14.,  6.,  5., 21.,
       12., 21., 12.,  3., 20.,  8., 16., 11., 18., 14.])

In [195]:
y_test

array([ 3,  2, 13, 18, 10, 13, 20, 20, 19, 21, 21, 20,  9, 20, 10, 20,  4,
       12, 12, 19,  9, 13, 13,  6,  5,  3, 20, 22, 13, 22, 10, 15, 20, 22,
       12, 10, 19,  9,  7, 12, 19,  9, 14, 20, 13,  6,  5, 19, 14,  5,  4,
       20, 13, 20, 13,  2, 20,  9, 16, 12, 19, 13], dtype=int64)

In [189]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_test,y_test_pred.round(), normalize=False)

26

In [186]:
model.score(X_test,y_test)

0.9829515859868385

In [196]:
confusion_matrix(y_test,y_test_pred.round())

array([[0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,